### ISSUE TITLE
Exception on Network.localhostIsIPv6() should be handled gracefully

### ISSUE THREAD

**Issue by whaley** [joelittlejohn/embedmongo-maven-plugin#13]
When working at local coffee shop I get the following on running the start goal.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.770s
[INFO] Finished at: Thu Mar 07 07:09:10 EST 2013
[INFO] Final Memory: 27M/354M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.joelittlejohn.embedmongo:embedmongo-maven-plugin:0.1.5:start (start) on project pem-system-tests-public-api-usage: Unable to determine if localhost is ipv6: capitalg: capitalg: nodename nor servname provided, or not known -> [Help 1]
[ERROR]
```

This also seems to happen if I disconnect myself and go offline.

In another maven module where I'm using de.flapdoodle.embed.mongo.MongodStarter in code as opposed to using your plugin as part of pre-integration-test and post-integration-test, I am wrapping MongodStarter jin this way to prevent that from happening.

```
public void startEmbeddedMongo() throws Exception {
    MongodConfig config = new MongodConfig(Version.V2_2_1, mongoPort, isLocalhostIPV6());
    MongodStarter runtime = MongodStarter.getDefaultInstance();
    mongod = runtime.prepare(config);
    mongod.start();
}

private boolean isLocalhostIPV6() {
    boolean isIp6;
    try {
        isIp6 = Network.localhostIsIPv6();
    } catch (Exception e) {
        isIp6 = false;
    }
    return isIp6;
}
```

If Network.localhostIsIPV6() fails for whatever reason, I'm just blithely setting MongodConfig's ipv6 property to false.

**Comment by joelittlejohn** [comment]
Note: there seems to be a problem calling functions like Network.localhostIsIPv6(), the result is an UnknownHostException with a message like:
```
jlittlej: jlittlej: nodename nor servname provided, or not known.
```
 If you experience this, the suggested workaround seems to be to add your hostname to `/etc/hosts`. 

In my case, this meant adding:

```
127.0.0.1    jlittlej
```

to `/etc/hosts`.
