### ISSUE TITLE
Add ability to specify init script for mongoDB.

### ISSUE THREAD

**Issue by duerlib** [joelittlejohn/embedmongo-maven-plugin#32]
I am having trouble finding a way to add some test data to the DB before my httptests are run. I am trying to use the @BeforeClass annotation but am unable to figure out what i need to do in that method to add something. I think it would be good if I could add a script file to the config of the plugin to be run once the DB is brought up. Any thoughts?

**Comment by pvardanega** [comment]
Hi,

I created a pull request https://github.com/joelittlejohn/embedmongo-maven-plugin/pull/40 to initialize data after a mongo instance is up and running.

**Comment by freemo** [comment]
I added this into my forked project too. Feel free to check it out. While the license isnt compatible it may give you some insight as to how you might want to merge this into your own project:

https://github.com/Syncleus/maven-mongodb-plugin
