### ISSUE TITLE
Allow to run using mongo:start

### ISSUE THREAD

**Issue by alexec** [joelittlejohn/embedmongo-maven-plugin#45]
You can set-up a goal prefix in pom.xml:

https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html

Then you can 

~~~
mvn mongo:start
~~~

**Comment by joelittlejohn** [comment]
Nice idea, thanks!

**Comment by joelittlejohn** [comment]
Fixed by 2351664.
