### ISSUE TITLE
Automatically choose collection names in mongoimport

### ISSUE THREAD

**Issue by yacota** [joelittlejohn/embedmongo-maven-plugin#48]
It woudl be awesome if the new mongo-import goal could use the name of the json files as collection's name. 
With this enhancement one could configure this goal like this

    <imports>
                    <import>
                        <file>NEWS.json,ASSET.json</file>
                    </import>
    </imports>

instead of

    <imports>
                    <import>
                        <collection>NEWS.</collection>
                        <file>NEWS.json</file>
                    </import>
                   <import>
                        <collection>ASSET</collection>
                        <file>ASSET.json</file>
                    </import>

    </imports>

There is a notably difference when working with a few dozens of collections :)

**Comment by yacota** [comment]
Actually being able to point to a filesystem directory would do the job

    <imports>
        <import>
               <filesDir>somePath</filesDir>
        </import>
    </imports>

**Comment by joelittlejohn** [comment]
Good point, I think the best option here would be to make the 'collection'
element optional.

**Comment by joelittlejohn** [comment]
I've made 'collection' optional which should help here. 

If you don't supply a value for collection, we'll use this part of the filename:

```
<file>./path/to/my/file.json</file>
                   ^^^^
```

So, the part after the last file separator and before the last `.` char.
