### ISSUE TITLE
Upgrade de.flapdoodle.embed.mongo in order to support MongoDb-3.x

### ISSUE THREAD

**Issue by yacota** [joelittlejohn/embedmongo-maven-plugin#50]
In order to be able to use MongoDB 3.x embedmongo-maven-plugin needs to upgrade its dependency de.flapdoodle.embed.mongo version to at least 1.47.1 (1.47.3 is the last tag from this branch)
For more info see below

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/119	

FYI I have tested my application with 1.50.0 and everything works fine

BTW : for the ones reading this and using https://github.com/jirutka/embedmongo-spring check that de.flapdoodle.embed.process dependency has the same version as de.flapdoodle.embed.mongo

**Comment by joelittlejohn** [comment]
Thanks @yacota, will upgrade this when I get a chance.

You mention that you tested your app with 1.50.0, do you mean you already testing embedmongo-maven-plugin with 1.50.0 and the upgrade was fine?

**Comment by yacota** [comment]
Yes, no problems so far

**Comment by joelittlejohn** [comment]
Ah, one problem here is that `version` isn't documented as a property of `mongo-import`. That would definitely help :)

**Comment by joelittlejohn** [comment]
I've updated to docs, hopefully that will make this more obvious.
