### ISSUE TITLE
Skip should apply to the stop goal

### ISSUE THREAD

**Issue by indriesergiu** [joelittlejohn/embedmongo-maven-plugin#55]
Hi,

I'm using a simple configuration like the one below in my parent pom which is inherited to all child poms. 

```xml
<plugin>
  <groupId>com.github.joelittlejohn.embedmongo</groupId>
  <artifactId>embedmongo-maven-plugin</artifactId>
  <version>0.3.0</version>
  <executions>
    <execution>
      <id>start</id>
      <goals>
        <goal>start</goal>
      </goals>
    </execution>
    <execution>
      <id>stop</id>
      <goals>
        <goal>stop</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

I run the command

```
mvn clean install -Dembedmongo.skip
```

The skip (-Dembedmongo.skip) option only applies to the start goal, which means that the stop goal will run and fail with

Failed to execute goal com.github.joelittlejohn.embedmongo:embedmongo-maven-plugin:0.3.0:stop (stop) on project pushnotification-persistence-mongo: No mongod process found, it appears embedmongo:start was not called

Maybe the skip flag should be global at plugin level. Or should the plugin be configured differently?

**Comment by joelittlejohn** [comment]
Thanks for reporting this. Skip should affect 'stop' too, you're right.

This should be trivial to add. We just need to add the skip property to the
stop goal and it should use the same property value 'embedmongo.skip'.

Happy for you to submit a PR for this, otherwise I'll add this when I get a
chance.

**Comment by joelittlejohn** [comment]
@indriesergiu looks good, feel free to submit a PR for this

**Comment by indriesergiu** [comment]
Already did :)

**Comment by joelittlejohn** [comment]
Doh! Sorry. Thanks!
