### ISSUE TITLE
Cant start mongodb 3.2.1 with mmapv1 storage engine

### ISSUE THREAD

**Issue by johanolsson76** [joelittlejohn/embedmongo-maven-plugin#62]
Hi and thanks for a great plugin.

I am however having problems with starting mongo DB 3.2.1 with storage engine mmapv1.
My maven config is:

```
<plugin>
	<groupId>com.github.joelittlejohn.embedmongo</groupId>
	<artifactId>embedmongo-maven-plugin</artifactId>
	<version>0.3.4</version>
	<executions>
		<execution>
			<id>start</id>
			<phase>pre-integration-test</phase>
			<goals>
				<goal>start</goal>
			</goals>
			<configuration>
				<storageEngine>mmapv1</storageEngine>
				<databaseDirectory>${basedir}/target/mongodb/${buildNumber}</databaseDirectory>
				<logging>none</logging>
				<port>${mongodb.port}</port>
				<version>3.2.1</version>
			</configuration>
		</execution>
		<execution>
			<id>stop</id>
			<phase>verify</phase>
			<goals>
				<goal>stop</goal>
			</goals>
			<configuration>
				<port>27015</port>
			</configuration>
		</execution>
	</executions>
</plugin>
```

But after startup i get the following when running:
```
connecting to: 127.0.0.1:27015/test
db.serverStatus().storageEngine
{ "name" : "wiredTiger", "supportsCommittedReads" : true }
> db.version()
3.2.1
```

**Comment by codescale** [comment]
Can you provide more info from the log?
I wonder if there is a line like this

`[INFO] [/tmp/extract-e07b7a92-fe02-4628-aaa6-91917d26eef0mongod, --dbpath, /mybuildworkspace/myproject/mongotest, --noauth, --noprealloc, --smallfiles, --nojournal, --storageEngine, mmapv1, --nohttpinterface, --port, 27017, --bind_ip, 127.0.0.1, --syncdelay=0]`

**Comment by johanolsson76** [comment]
Hi.
I don't see any logging like this. The following is logged when the plugin starts:
```
Extract C:\Users\tester\.embedmongo\win32\mongodb-win32-x86_64-2008plus-3.2.1.zip START
Extract C:\Users\tester\.embedmongo\win32\mongodb-win32-x86_64-2008plus-3.2.1.zip extract mongodb-win32-x86_64-2008plus-3.2.1/bin/mongod.exe
Extract C:\Users\tester\.embedmongo\win32\mongodb-win32-x86_64-2008plus-3.2.1.zip noting left
Extract C:\Users\tester\.embedmongo\win32\mongodb-win32-x86_64-2008plus-3.2.1.zip DONE
[main] INFO de.flapdoodle.embed.process.runtime.Executable - start de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@15dab177
````

**Comment by joelittlejohn** [comment]
@codescale with the example config that @johanolsson76 gave above, I see this in my process list:

```
/var/folders/2f/0p_7h92j2mgft7hqwtg6q9840000gn/T/extract-4f9d825a-4975-4f4d-9576-51c02413629cmongod --dbpath /Users/jlittlej/workspace/embedmongo-maven-plugin/src/test/resources/example1/target/mongodb/${buildNumber} --noauth --noprealloc --smallfiles --nojournal --nohttpinterface --port 27017
```

**Comment by codescale** [comment]
The problem here is `de.flapdoodle.embed.mongo` they don't include the MongoDB version 3.2.1 yet. As the `storageEngine`parameter is new it falls back to the default (which means, the `storageEngine` parameter is skipped. That means MongoDB starts up with the default `storageEngine` which is `wiredTiger` in case of 3.2.1)

You could fix this. Either by adding a pull-request to `de.flapdoodle.embed.mongo` or using the supported versions `3.2.0` or `3.2.1-rc3` (see the [Version.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/de.flapdoodle.embed.mongo-1.50.2/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java) file in `de.flapdoodle.embed.mongo` for more detail.)

**Comment by johanolsson76** [comment]
Thanks for your support. Will use 3.2.0 for now.

**Comment by codescale** [comment]
Glad i could help :)
