### ISSUE TITLE
journal option on configuration doesn't seems picks

### ISSUE THREAD

**Issue by codethala** [joelittlejohn/embedmongo-maven-plugin#63]
threw exception; nested exception is com.mongodb.MongoCommandException: Command failed with error 2: 'cannot use 'j' option when a host does not have journaling enabled' on server localhost:27017. The full response is { "ok" : 0, "code" : 2, "errmsg" : "cannot use 'j' option when a host does not have journaling enabled" }

`						<groupId>com.github.joelittlejohn.embedmongo</groupId>
						<artifactId>embedmongo-maven-plugin</artifactId>
						<version>0.3.5-SNAPSHOT</version>
						<executions>
							<execution>
							<id>start</id>
								<goals>
									<goal>start</goal>
								</goals>
								<configuration>
									<port>27017</port>
									<randomPort>false</randomPort>
									<version>3.2.1</version>
									<databaseDirectory>${project.build.directory}/mongotest</databaseDirectory>
									<bindIp>127.0.0.1</bindIp>
									<journal>true</journal>
								</configuration>
								</execution>
								<execution>
									<id>stop</id>
								<goals>
									<goal>stop</goal>
								</goals>
							</execution>`

**Comment by joelittlejohn** [comment]
Which version of mongodb are you using?

**Comment by selvathira** [comment]
I tried to put some debug points and installed to see if its picking. Yes!!! it does, but am keep getting this same error. -> "cannot use 'j' option when a host does not have journaling enabled' "

**Comment by joelittlejohn** [comment]
I expect this is because the underlying flapdoodle api only activates
features like journalling if it knows that the version you have chosen
supports it. That API has not yet been updated to invoked 3.2.1 as far as I
know, so this means it doesn't know which features it supports.

Could you try with 3.2.0?

**Comment by codescale** [comment]
Hi @selvathira ,
can i be that you run this on a 32-bit machine? `de.flapdoodle.embed.mongo`passes the command `--nojournal`and not `--journal` (as you can see in their code [Mongod.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/de.flapdoodle.embed.mongo-1.50.2/src/main/java/de/flapdoodle/embed/mongo/runtime/Mongod.java) ).

**Comment by selvathira** [comment]
@joelittlejohn,  thanks. 3.2.0 worked fine.

@codescale,i Its 64 bit. I debugged the plugin, it picks the journal and sets it noJournal correctly.

**Comment by joelittlejohn** [comment]
This has come up recently, related to a different command line option. The best route to fixing this would be to submit a PR to the flapdoodle embedmongo project to include 3.2.1 in the list of known versions.

**Comment by joelittlejohn** [comment]
See flapdoodle-oss/de.flapdoodle.embed.mongo#150. We need another PR for 3.2.5 already :)

**Comment by asarkar** [comment]
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/150 has been merged but I'm still getting the same error as the OP. I've added `writeConcern=journaled` as a query param, and that seems to do the job for external Mongo, but not embedded. I opened https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/222, but then stumbled across this issue. Am I missing something?

**Comment by joelittlejohn** [comment]
@asarkar Sounds like the same issue, explained in https://github.com/joelittlejohn/embedmongo-maven-plugin/issues/63#issuecomment-183050126

It looks like embedmongo does not know about 3.4.1, hence it does not know what features it has. You need to submit a PR to flapdoodle-oss/de.flapdoodle.embed.mongo to include 3.4.1 here:

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java

Then we will need to update this plugin to include the new version of flapdoodle-oss/de.flapdoodle.embed.mongo.
