### ISSUE TITLE
how to consum the mongodb file from Nexus only

### ISSUE THREAD

**Issue by songwk** [joelittlejohn/embedmongo-maven-plugin#65]
Hi,
There is a problem on the Jenkin server, it only allows to download dependency from company Nexus.
So the plugin can't download the db file outside of company.  After I upload the DB file to Nexus,  whether the plugin could get it from Nexus. 

I just know a stupid solution, that is to add the db file to my project, the file too big. Is there other solutions to prepare the db file for the plugin? 

Best regards

**Comment by joelittlejohn** [comment]
If you want to download a file from Nexus you can use the Maven dependency plugin. Download the file before invoking the embedmongo-maven-plugin.
