### ISSUE TITLE
On Windows failed downloadPath with protocol file

### ISSUE THREAD

**Issue by baudointran** [joelittlejohn/embedmongo-maven-plugin#66]
On windows seven,

<configuration>
<downloadPath>file:///${project.basedir}/src.resources/</downloadPath>

running with
mvn monogo:start

I have 
[ERROR] Failed to execute goal com.github.joelittlejohn.embedmongo:embedmongo-maven-plugin:0.3.4:start (default-cli) on project questionnaire: Execution default-cli of goal com.github.joelittlejohn.embedmongo:embedmongo-maven-plugin:0.3.4:start failed: Illegal character in path at index 10: file:///E:\...../resources/mongo/ -> [Help 1]

**Comment by joelittlejohn** [comment]
file:// URIs are not supported I'm afraid.

**Comment by joelittlejohn** [comment]
Another option here would be to populate your local Mongo binaries cache instead. You'll find it in `~/.embedmongo`.
