### ISSUE TITLE
Can I use this for a hooked mongoDB?

### ISSUE THREAD

**Issue by xetra11** [joelittlejohn/embedmongo-maven-plugin#67]
Hello,
I am curious if I could use this plugin to start a mongoDB together with a tomcat + webapp.
ATM I am tired of starting a mongo instance by hand every time I run the webapp. Because the webapp does start without it but is very slowly. Therefore I'd like not to care about this anymore and just run my goal and see the mongoDB starting with it as well.

again - is this possible with this plugin?

**Comment by joelittlejohn** [comment]
Hi, sorry for the delay. I read this but forgot to reply.

It certainly sounds like you could use this plugin for what you need. Do you start your app in a particular Maven phase? The simples thing is to start your app during a maven phase, and bind this embedmongo-maven-plugin to that same phase or before.

**Comment by xetra11** [comment]
sounds good - will try it out. Thank you!
