### ISSUE TITLE
Can I update the project to Java 8?

### ISSUE THREAD

**Issue by adamretter** [joelittlejohn/embedmongo-maven-plugin#74]
If I sent a PR which updates everything to the latest versions for Java 8, such as de.flapdoodle.embed.mongo version 2, would it be accepted? or is this project determined to stay with Java 6 compatibility?

**Comment by joelittlejohn** [comment]
Java 8 was released over 4 years ago so I'm happy to move forward in this project. Let's increment the major version for Java 8.
