### ISSUE TITLE
release 0.4.1

### ISSUE THREAD

**Issue by fnspecter69** [joelittlejohn/embedmongo-maven-plugin#82]
Can you tag 0.4.1 with the updated version of flapdoodle embed-mongo.

**Comment by joelittlejohn** [comment]
Can you send a PR please?

**Comment by juliovalcarcel** [comment]
Any update for this? Using the snapshot build of the plugin works  for mongo 3.6.5 but when running it with 0.4.0 we are getting an error:

```
[mongod error]Error parsing command line: unrecognised option '--nohttpinterface'
```
